// =============================================================================
// Refine Command - Refine PRD, plan, or other project documents
// =============================================================================

import { existsSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import chalk from "chalk";
import { ClaudeAgentProvider } from "../agents";
import { findGitRoot } from "./context";

// =============================================================================
// File Selection
// =============================================================================

interface RefineFile {
  name: string;
  description: string;
  nextStep: string;
  nextCommand: string;
}

const REFINE_FILES: RefineFile[] = [
  {
    name: "PRD.md",
    description: "Product Requirements Document - defines WHAT to build and WHY",
    nextStep: "Create implementation plan from PRD",
    nextCommand: "bloom plan",
  },
  {
    name: "plan.md",
    description: "Implementation Plan - defines HOW to build it",
    nextStep: "Generate tasks.yaml for execution",
    nextCommand: "bloom generate",
  },
  {
    name: "tasks.yaml",
    description: "Task Definitions - machine-readable tasks for agents",
    nextStep: "Execute tasks with agents",
    nextCommand: "bloom run",
  },
  {
    name: "CLAUDE.md",
    description: "Guidelines for Claude agents working on this project",
    nextStep: "Continue with your workflow",
    nextCommand: "",
  },
];

async function selectFileToRefine(workingDir: string): Promise<RefineFile | null> {
  const select = (await import("@inquirer/select")).default;

  // Find which files exist
  const existingFiles = REFINE_FILES.filter((f) => existsSync(join(workingDir, f.name)));

  if (existingFiles.length === 0) {
    return null;
  }

  const choices = existingFiles.map((f) => ({
    name: `${chalk.cyan(f.name)} ${chalk.dim("-")} ${f.description}`,
    value: f,
  }));

  const selected = await select({
    message: "Which file would you like to refine?",
    choices,
  });

  return selected;
}

// =============================================================================
// Run Refine Session
// =============================================================================

export async function runRefineSession(workingDir: string, selectedFile: RefineFile): Promise<void> {
  const gitRoot = findGitRoot() || workingDir;

  // Build context about what files exist in the project
  const projectFiles: string[] = [];
  if (existsSync(workingDir)) {
    const files = readdirSync(workingDir);
    for (const file of files) {
      const filePath = join(workingDir, file);
      const stat = statSync(filePath);
      if (stat.isFile() && (file.endsWith(".md") || file.endsWith(".yaml") || file.endsWith(".yml"))) {
        projectFiles.push(file);
      }
    }
  }

  const filesContext =
    projectFiles.length > 0
      ? `Available files in project:\n${projectFiles.map((f) => `  - ${f}`).join("\n")}`
      : "No markdown or yaml files found in the project directory.";

  const systemPrompt = `You are helping refine project documentation in a Bloom workspace.

Working Directory: ${workingDir}
Git Root: ${gitRoot}

${filesContext}

Your role is to help the user refine their project documents. The key files are:

**PRD.md** - Product Requirements Document (start here!)
- Defines WHAT to build and WHY
- Should have clear problem statement, target users, goals, features
- This is the foundation - get this right before planning

**plan.md** - Implementation Plan
- Defines HOW to build it
- Breaks work into phases with clear tasks and acceptance criteria
- Created by 'bloom plan' from the PRD

**tasks.yaml** - Task Definitions (for execution)
- Machine-readable tasks for agents to execute
- Generated by 'bloom generate' from plan.md
- Can be refined to adjust task details, dependencies, or agent assignments

**CLAUDE.md** - Guidelines for Claude agents
- Project-specific instructions for Claude when working on tasks
- Code standards, patterns, conventions to follow

You can read files from anywhere in the git repository to gather context (repos/, other projects, etc.), but you should only modify files in the current project directory: ${workingDir}

When helping the user:
1. Read the target file first to understand its current state
2. Ask clarifying questions to understand what they want to change
3. Suggest specific improvements with clear reasoning
4. Make edits when the user approves

Focus on making documents clear, complete, and actionable.`;

  const agent = new ClaudeAgentProvider({
    interactive: true,
    dangerouslySkipPermissions: true,
  });

  console.log(`${chalk.bold("Refining:")} ${chalk.cyan(selectedFile.name)}\n`);

  const initialPrompt = `I want to refine ${selectedFile.name}. Please read it first and help me improve it.`;

  await agent.run({
    systemPrompt,
    prompt: initialPrompt,
    startingDirectory: workingDir,
  });
}

// =============================================================================
// Command Handler
// =============================================================================

export async function cmdRefine(): Promise<void> {
  const workingDir = process.cwd();

  // Ask user which file to refine
  const selectedFile = await selectFileToRefine(workingDir);

  if (!selectedFile) {
    console.log(chalk.yellow("No project files found in the current directory.\n"));
    console.log(chalk.bold("Typical project files:"));
    console.log(`  ${chalk.cyan("PRD.md")}      - Product Requirements Document`);
    console.log(`  ${chalk.cyan("plan.md")}     - Implementation plan`);
    console.log(`  ${chalk.cyan("tasks.yaml")}  - Task definitions`);
    console.log(`  ${chalk.cyan("CLAUDE.md")}   - Guidelines for Claude\n`);
    console.log(chalk.dim("Run 'bloom create <name>' to create a new project with templates."));
    process.exit(1);
  }

  await runRefineSession(workingDir, selectedFile);

  console.log(chalk.dim(`\n---`));
  console.log(chalk.green("Refine session complete."));

  // Show next step based on selected file
  if (selectedFile.nextCommand) {
    console.log(
      `\n${chalk.bold("Next:")} ${chalk.cyan(selectedFile.nextCommand.padEnd(16))} ${chalk.dim("#")} ${selectedFile.nextStep}`
    );
  }
}
