// =============================================================================
// Refine Command - Refine PRD, plan, or other project documents
// =============================================================================

import { existsSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { ClaudeAgentProvider } from "../agents";
import { findGitRoot } from "./context";

// =============================================================================
// Run Refine Session
// =============================================================================

export async function runRefineSession(workingDir: string): Promise<void> {
  const gitRoot = findGitRoot() || workingDir;

  // Build context about what files exist in the project
  const projectFiles: string[] = [];
  if (existsSync(workingDir)) {
    const files = readdirSync(workingDir);
    for (const file of files) {
      const filePath = join(workingDir, file);
      const stat = statSync(filePath);
      if (stat.isFile() && (file.endsWith(".md") || file.endsWith(".yaml") || file.endsWith(".yml"))) {
        projectFiles.push(file);
      }
    }
  }

  const filesContext =
    projectFiles.length > 0
      ? `Available files in project:\n${projectFiles.map((f) => `  - ${f}`).join("\n")}`
      : "No markdown or yaml files found in the project directory.";

  const systemPrompt = `You are helping refine project documentation in a Bloom workspace.

Working Directory: ${workingDir}
Git Root: ${gitRoot}

${filesContext}

Your role is to help the user refine their project documents. The key files are:

**PRD.md** - Product Requirements Document (start here!)
- Defines WHAT to build and WHY
- Should have clear problem statement, target users, goals, features
- This is the foundation - get this right before planning

**plan.md** - Implementation Plan
- Defines HOW to build it
- Breaks work into phases with clear tasks and acceptance criteria
- Created by 'bloom plan' from the PRD

**tasks.yaml** - Task Definitions (for execution)
- Machine-readable tasks for agents to execute
- Generated by 'bloom generate' from plan.md
- Can be refined to adjust task details, dependencies, or agent assignments

**CLAUDE.md** - Guidelines for Claude agents
- Project-specific instructions for Claude when working on tasks
- Code standards, patterns, conventions to follow

You can read files from anywhere in the git repository to gather context (repos/, other projects, etc.), but you should only modify files in the current project directory: ${workingDir}

When helping the user:
1. Ask clarifying questions to understand their goals
2. Read existing documents to understand current state
3. Suggest specific improvements with clear reasoning
4. Make edits when the user approves

Focus on making documents clear, complete, and actionable.`;

  const agent = new ClaudeAgentProvider({
    interactive: true,
    dangerouslySkipPermissions: true,
  });

  console.log(`Refine session for: ${workingDir}\n`);
  console.log(`You can refine PRD.md, plan.md, CLAUDE.md, or any other documents.`);
  console.log(`Claude can read context from the entire workspace but will only edit files in this project.\n`);

  await agent.run({
    systemPrompt,
    prompt: "",
    startingDirectory: workingDir,
  });
}

// =============================================================================
// Command Handler
// =============================================================================

export async function cmdRefine(): Promise<void> {
  const workingDir = process.cwd();

  // Check what project files exist
  const hasPrd = existsSync(join(workingDir, "PRD.md"));
  const hasPlan = existsSync(join(workingDir, "plan.md"));
  const hasTasks = existsSync(join(workingDir, "tasks.yaml"));
  const hasClaudeMd = existsSync(join(workingDir, "CLAUDE.md"));

  // Show helpful context about what exists
  if (!hasPrd && !hasPlan && !hasClaudeMd && !hasTasks) {
    console.log("No project files found in the current directory.\n");
    console.log("Typical project files:");
    console.log("  PRD.md      - Product Requirements Document");
    console.log("  plan.md     - Implementation plan");
    console.log("  tasks.yaml  - Task definitions");
    console.log("  CLAUDE.md   - Guidelines for Claude\n");
    console.log("You can:");
    console.log("  - Run 'bloom create <name>' to create a new project with templates");
    console.log("  - Continue anyway to create files from scratch\n");
  }

  await runRefineSession(workingDir);

  console.log(`\n---`);
  console.log(`Refine session complete.`);

  // Show contextual next steps
  if (!hasPlan && hasPrd) {
    console.log(`\nNext: bloom plan      # Create implementation plan from PRD`);
  } else if (!hasTasks && hasPlan) {
    console.log(`\nNext: bloom generate  # Generate tasks.yaml from plan`);
  } else if (hasTasks) {
    console.log(`\nNext: bloom run       # Execute tasks`);
  } else {
    console.log(`\nNext steps:`);
    console.log(`  bloom plan          # Create implementation plan`);
    console.log(`  bloom generate      # Generate tasks.yaml from plan`);
    console.log(`  bloom run           # Execute tasks`);
  }
}
